"""initial schema

Revision ID: 7508884988c7
Revises: 
Create Date: 2025-12-15 13:10:25.466840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7508884988c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('hostname', sa.Text(), nullable=False),
    sa.Column('cli_port', sa.Integer(), nullable=False),
    sa.Column('webadmin_port', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('encrypted_password', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('taken_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('servers_count', sa.Integer(), nullable=True),
    sa.Column('domains_count', sa.Integer(), nullable=True),
    sa.Column('accounts_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('domain_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('local_part', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('old_assigned_mb', sa.Integer(), nullable=True),
    sa.Column('new_assigned_mb', sa.Integer(), nullable=True),
    sa.Column('happened_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['snapshots.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_account_changes_email_happened_at', 'account_changes', ['email', 'happened_at'], unique=False)
    op.create_index('ix_account_changes_server_id_happened_at', 'account_changes', ['server_id', 'happened_at'], unique=False)
    op.create_table('domain_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('domain_name', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('old_status', sa.Text(), nullable=True),
    sa.Column('new_status', sa.Text(), nullable=True),
    sa.Column('happened_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['snapshots.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_domain_changes_server_id_happened_at', 'domain_changes', ['server_id', 'happened_at'], unique=False)
    op.create_table('domains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('total_accounts', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('state_hash', sa.Text(), nullable=True),
    sa.Column('snapshot_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'name', name='uq_domains_server_id_name')
    )
    op.create_index('ix_domains_server_id', 'domains', ['server_id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain_id', sa.UUID(), nullable=False),
    sa.Column('local_part', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('assigned_mb', sa.Integer(), nullable=True),
    sa.Column('used_mb', sa.Numeric(), nullable=True),
    sa.Column('free_mb', sa.Numeric(), nullable=True),
    sa.Column('last_seen_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('quota_hash', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('snapshot_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'local_part', name='uq_accounts_domain_id_local_part')
    )
    op.create_index('ix_accounts_domain_id', 'accounts', ['domain_id'], unique=False)
    op.create_index('ix_accounts_email', 'accounts', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_accounts_email', table_name='accounts')
    op.drop_index('ix_accounts_domain_id', table_name='accounts')
    op.drop_table('accounts')
    op.drop_index('ix_domains_server_id', table_name='domains')
    op.drop_table('domains')
    op.drop_index('ix_domain_changes_server_id_happened_at', table_name='domain_changes')
    op.drop_table('domain_changes')
    op.drop_index('ix_account_changes_server_id_happened_at', table_name='account_changes')
    op.drop_index('ix_account_changes_email_happened_at', table_name='account_changes')
    op.drop_table('account_changes')
    op.drop_table('snapshots')
    op.drop_table('servers')
    # ### end Alembic commands ###
